---
version: 2
archives:
  - id: archive
    name_template: '{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}'
    files:
      - plugin.conf
before:
  hooks:
    - go mod download
builds:
  - main: ./cmd/
    binary: telegraf-output-kinesis-data-firehose
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goarch:
      - amd64
      - arm64
    goos:
      - darwin
      - windows
      - linux
    ldflags:
      - -X github.com/muhlba91/telegraf-output-kinesis-data-firehose/plugins/outputs/firehose/version.Version={{ .Tag }}
source:
  enabled: true
signs:
  - cmd: cosign
    env:
      - COSIGN_EXPERIMENTAL=1
    certificate: '${artifact}.pem'
    args:
      - sign-blob
      - --yes
      - '--output-certificate=${certificate}'
      - '--bundle=${signature}'
      - '${artifact}'
    artifacts: all
    output: true
sboms:
  - artifacts: archive
  - id: source
    artifacts: source
changelog:
  disable: true
  use: github
  filters:
    exclude:
      - '^docs'
      - '^chore'
  groups:	
    - title: 'New Features'	
      regexp: "^.*feat[(\\w)]*:+.*$"	
      order: 0	
    - title: 'Bugfixes'	
      regexp: "^.*fix[(\\w)]*:+.*$"	
      order: 10	
    - title: Other Work	
      order: 999
release:
  disable: false
  prerelease: auto
snapshot:
  name_template: '{{ .Tag }}-SNAPSHOT'
