---
name: Pipeline

on:
  pull_request:
  push:
    branches:
      - main
    paths-ignore:
      - CHANGELOG.md
  workflow_dispatch:

env:
  GO111MODULE: "on"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Plugin
    strategy:
      max-parallel: 4
      matrix:
        go-version: [ 1.19.x ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '${{ matrix.go-version }}'

      - name: Build
        run: make build

  lint:
    runs-on: ubuntu-latest
    name: Lint Plugin
    strategy:
      max-parallel: 4
      matrix:
        go-version: [ 1.19.x ]
        golangci-lint-version: [ v1.53.1]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '${{ matrix.go-version }}'

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: '${{ matrix.golangci-lint-version }}'
          args: -c .golangci.yml
          skip-pkg-cache: true
          skip-build-cache: true

  tests:
    runs-on: ubuntu-latest
    name: Run Tests
    strategy:
      matrix:
        go-version: [ 1.19.x ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '${{ matrix.go-version }}'

      - name: Run Tests
        run: make test
        
      - name: Coveralls
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: coverage.out

  snyk:
    runs-on: ubuntu-latest
    name: Snyk Scanning

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Snyk Monitor
        uses: snyk/actions/golang@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor

      - name: Snyk Test
        uses: snyk/actions/golang@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=medium --fail-on=all --sarif-file-output=snyk.sarif

  tag:
    runs-on: ubuntu-latest
    name: Tag Release
    permissions:
      contents: write
      id-token: write
    if: github.ref == 'refs/heads/main'
    needs:
      - build
      - lint
      - tests
      - snyk

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: '${{ secrets.GH_PUSH_TOKEN }}'
      - name: Setup Git
        run: |
          git config --local user.email "${{ env.GITHUB_ACTION }}+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git fetch --tags
      - name: Versioning and Changelog
        run: |
          npx standard-version
      - name: Push to Repository
        run: |
          git push --follow-tags
