---
name: Pull Request

on:
  pull_request:

env:
  GO111MODULE: "on"

jobs:
  snyk:
    runs-on: ubuntu-latest
    name: Snyk Scanning

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Snyk Test
        uses: snyk/actions/golang@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=medium --fail-on=all --sarif-file-output=snyk.sarif

      - name: Upload Snyk Result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif
